<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260905000200 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Bounded report results and transactional Doctrine Messenger transport.';
    }

    public function up(Schema $schema): void
    {
        $sql = <<<'SQL'
CREATE TABLE report_job (id UUID PRIMARY KEY, requester_id UUID NOT NULL REFERENCES app_user(id), from_at TIMESTAMPTZ NOT NULL, to_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL, status VARCHAR(16) NOT NULL CHECK (status IN ('pending','ready','failed')), generated_at TIMESTAMPTZ DEFAULT NULL, row_count INT DEFAULT NULL, csv TEXT DEFAULT NULL, failure_code VARCHAR(48) DEFAULT NULL,
 CHECK (to_at > from_at AND to_at - from_at <= INTERVAL '31 days'),
 CHECK (row_count IS NULL OR row_count BETWEEN 0 AND 10000),
 CHECK (csv IS NULL OR octet_length(csv) <= 5242880),
 CHECK ((status='ready') = (generated_at IS NOT NULL AND row_count IS NOT NULL AND csv IS NOT NULL)),
 CHECK ((status='failed') = (failure_code IS NOT NULL)));
CREATE INDEX IDX_2DC8224FED442CF4 ON report_job (requester_id);
CREATE UNIQUE INDEX one_pending_report ON report_job (requester_id) WHERE (status = 'pending'::text);
CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL);
CREATE INDEX messenger_queue_delivery ON messenger_messages (queue_name,available_at,delivered_at,id);
GRANT SELECT,INSERT,UPDATE,DELETE ON report_job,messenger_messages TO desk_runtime;
GRANT USAGE,SELECT ON SEQUENCE messenger_messages_id_seq TO desk_runtime;
SQL;
        foreach (explode(';', $sql) as $statement) {
            if ('' !== trim($statement)) {
                $this->addSql(trim($statement));
            }
        }
    }

    public function down(Schema $schema): void
    {
        $this->throwIrreversibleMigrationException('Report rollback requires preserving results and queue state in a verified backup.');
    }
}
